$ErrorActionPreference = "Stop"

$root = "c:\Users\LENOVO\Desktop\prompt bank"
$jsonPath = Join-Path $root "prompt_bank_data.json"
$htmlPath = Join-Path $root "PromptBank_Full_Database_Report.html"
$pdfPath = Join-Path $root "PromptBank_Full_Database_Report.pdf"

if (-not (Test-Path $jsonPath)) {
  throw "Missing file: $jsonPath"
}

$items = Get-Content -Raw -Path $jsonPath | ConvertFrom-Json
if ($null -eq $items -or $items.Count -eq 0) {
  throw "No prompt records found in prompt_bank_data.json"
}

function Escape-Html([string]$text) {
  if ($null -eq $text) { return "" }
  return [System.Net.WebUtility]::HtmlEncode($text)
}

function To-ImageKind([string]$src) {
  if ([string]::IsNullOrWhiteSpace($src)) { return "None" }
  if ($src.StartsWith("data:image")) { return "Embedded (base64)" }
  if ($src.StartsWith("http://") -or $src.StartsWith("https://")) { return "Remote URL" }
  return "Local/Relative file"
}

$generatedOn = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$total = $items.Count

$rows = New-Object System.Text.StringBuilder
$cards = New-Object System.Text.StringBuilder

for ($i = 0; $i -lt $items.Count; $i++) {
  $p = $items[$i]
  $idx = $i + 1

  $id = Escape-Html ([string]$p.id)
  $title = Escape-Html ([string]$p.title)
  $category = Escape-Html ([string]$p.category)
  $tagline = Escape-Html ([string]$p.tagline)
  $promptText = Escape-Html ([string]$p.prompt)
  $mainImage = [string]$p.mainImage
  $imageKind = Escape-Html (To-ImageKind $mainImage)
  $featured = if ($p.featuredInSlider) { "Yes" } else { "No" }
  $imagesCount = if ($p.images) { $p.images.Count } else { 0 }

  [void]$rows.AppendLine("<tr><td>$idx</td><td>$id</td><td>$title</td><td>$category</td><td>$imagesCount</td><td>$featured</td></tr>")

  [void]$cards.AppendLine("<section class='card'>")
  [void]$cards.AppendLine("<h3>$idx. $title</h3>")
  [void]$cards.AppendLine("<p><strong>ID:</strong> $id</p>")
  [void]$cards.AppendLine("<p><strong>Category:</strong> $category</p>")
  [void]$cards.AppendLine("<p><strong>Tagline:</strong> $tagline</p>")
  [void]$cards.AppendLine("<p><strong>Featured In Slider:</strong> $featured</p>")
  [void]$cards.AppendLine("<p><strong>Main Image Type:</strong> $imageKind</p>")
  [void]$cards.AppendLine("<p><strong>Total Images:</strong> $imagesCount</p>")
  [void]$cards.AppendLine("<h4>Prompt Content</h4>")
  [void]$cards.AppendLine("<pre>$promptText</pre>")
  [void]$cards.AppendLine("</section>")
}

$html = @"
<!DOCTYPE html>
<html lang='en'>
<head>
  <meta charset='UTF-8' />
  <meta name='viewport' content='width=device-width, initial-scale=1.0' />
  <title>Prompt Bank Full Database Report</title>
  <style>
    body { margin: 0; padding: 28px; font-family: "Segoe UI", Tahoma, sans-serif; color: #111; background: #fff; line-height: 1.5; }
    .wrap { max-width: 1000px; margin: 0 auto; }
    h1 { margin: 0 0 8px; font-size: 32px; }
    h2 { margin: 26px 0 10px; font-size: 22px; border-left: 4px solid #ff5a2f; padding-left: 10px; }
    h3 { margin: 0 0 8px; font-size: 18px; }
    h4 { margin: 12px 0 8px; font-size: 15px; color: #1d2d4f; }
    p { margin: 6px 0; }
    .muted { color: #5f5f5f; }
    .summary { border: 1px solid #d9d9d9; background: #f7f7f7; padding: 12px; border-radius: 8px; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th, td { border: 1px solid #d7d7d7; padding: 8px; text-align: left; vertical-align: top; }
    th { background: #f1f1f1; }
    .card { border: 1px solid #dcdcdc; border-radius: 8px; padding: 12px; margin-top: 12px; background: #fafafa; page-break-inside: avoid; }
    pre { white-space: pre-wrap; word-break: break-word; background: #fff; border: 1px solid #e1e1e1; border-radius: 6px; padding: 10px; font-size: 13px; }
    .footer { margin-top: 20px; border-top: 1px dashed #c4c4c4; padding-top: 8px; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <div class='wrap'>
    <h1>Prompt Bank Full Database Report</h1>
    <p class='muted'>Complete prompt database export in readable format.</p>

    <div class='summary'>
      <p><strong>Total Records:</strong> $total</p>
      <p><strong>Source File:</strong> prompt_bank_data.json</p>
      <p><strong>Generated On:</strong> $generatedOn</p>
      <p><strong>Note:</strong> Image binary/base64 content is not printed fully to keep PDF readable. Prompt text data is fully included.</p>
    </div>

    <h2>Record Index</h2>
    <table>
      <thead>
        <tr><th>#</th><th>ID</th><th>Title</th><th>Category</th><th>Images</th><th>Featured</th></tr>
      </thead>
      <tbody>
        $($rows.ToString())
      </tbody>
    </table>

    <h2>Full Prompt Records</h2>
    $($cards.ToString())

    <div class='footer'>Generated by build_database_report.ps1</div>
  </div>
</body>
</html>
"@

Set-Content -Path $htmlPath -Value $html -Encoding UTF8
Write-Output "HTML_CREATED=$htmlPath"
Write-Output "PDF_TARGET=$pdfPath"
